services:
  flow_monitoring.monitor.flow:
    class: FlowMonitoringBundle\Monitor\Flow
    arguments:
      - '@akeneo_batch.job_repository'
      - '@akeneo_batch_queue.queue.database_job_execution_queue'
      - '@doctrine'


  flow_monitoring.monitor.monitor:
    class: FlowMonitoringBundle\Monitor\Monitor
